services:
  - type: web
    name: url-rotator-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: SOURCE_URL
        value: "https://ampnyapunyaku.top/api/render-cyber-lockdown-image/node.txt"
      - key: REQUEST_TIMEOUT
        value: "60000"
      - key: CORS_PROXY
        value: "https://cors-anywhere-vercel-dzone.vercel.app/"
      - key: USE_PROXY
        value: "0"   # 0 = OFF (langsung ke target), 1 = ON (pakai proxy)
