services:
  - type: web
    name: url-rotator-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: SOURCE_URL
        value: "https://ampnyapunyaku.top/api/render-cyber-lockdown-image/node.txt"
      - key: REQUEST_TIMEOUT
        value: "60000"   # boleh 30000 kalau mau lebih agresif
      - key: CORS_PROXY
        value: "https://cors-anywhere-vercel-dzone.vercel.app/"
