services:
  - type: web
    name: url-rotator-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: SOURCE_URL
        value: "https://domainsaya.com/node.txt"
      - key: LOOP_DELAY
        value: "3"
      - key: REQUEST_TIMEOUT
        value: "60000"
      - key: PER_URL_DELAY_MS
        value: "2000"
      - key: CORS_PROXY
        value: "https://cors-anywhere-vercel-dzone.vercel.app/"
      # set ini ke "1" kalau proxy kamu butuh target URL di-encodeURIComponent
      - key: USE_ENCODED
        value: "0"
