services:
  - type: web
    name: url-rotator-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: SOURCE_URL
        value: "https://ampnyapunyaku.top/api/render-cyber-lockdown-image/node.txt"   # ganti dengan URL node.txt kamu
      - key: LOOP_DELAY
        value: "3"
      - key: REQUEST_TIMEOUT
        value: "60000"
      - key: PER_URL_DELAY_MS
        value: "1000"
      - key: CORS_PROXY
        value: "https://cors-anywhere-vercel-dzone.vercel.app/"
      # set "1" jika proxy kamu butuh target URL di-encodeURIComponent
      - key: USE_ENCODED
        value: "0"
